services:
  mongo:
    image: mongo:7
    container_name: electroshop-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: electroshop-api
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
      MONGO_URI: "mongodb://mongo:27017/electroshop"
      JWT_SECRET: "change_me"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
